---
- hosts: mywebservers
  become: yes
  tasks:
  - name:  install webserver on debian node only
    apt: 
     name: "{{mywebpackageforubnutu}}"
     state: present
    when: ansible_os_family =="Debian"
    
  - name: install webserver on RedHat node only
    yum:
      name: "{{mywebpackageforredhat}}"
      state: present
    when: ansible_os_family=="RedHat"